openapi: 3.0.3
info:
  title: BankApi
  description: CRUD API для управления банковскими картами
  version: 1.0.0
paths:
  /api/admin/card/get_all:
    get:
      tags:
        - Card
      summary: Получить список всех карт
      operationId: getAllCards
      responses:
        '200':
          description: Список карт
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CardWithUserIdDto'
  /api/admin/card/create:
    post:
      tags:
        - Card
      summary: Создать новую карту
      operationId: createCard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardWithUserIdDto'
      responses:
        '201':
          description: Создана карта
  /api/admin/card/get/{id}:
    get:
      tags:
        - Card
      summary: Получить карту по ID
      operationId: getCardById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Карта
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardWithUserIdDto'
        '404':
          description: Карта не найдена
  /api/admin/card/update/{id}:
    put:
      tags:
        - Card
      summary: Обновить карту по ID
      operationId: updateCard
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardWithUserIdDto'
      responses:
        '200':
          description: Обновлена карта
        '404':
          description: Карта не найдена
  /api/admin/card/block/{id}:
    put:
      tags:
        - Card
      summary: Заблокировать карту по ID
      operationId: blockCard
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Карта успешно заблокирована
        '404':
          description: Карта не найдена
  /api/admin/card/delete/{id}:
    delete:
      tags:
        - Card
      summary: Удалить карту по ID
      operationId: deleteCard
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Карта удалена
  /api/user/card/get_filter_cards:
    get:
      tags:
        - Card
      summary: Получить список своих карт
      operationId: getUserCards
      parameters:
        - name: page
          in: query
          description: Номер страницы (начинается с 0)
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: Количество элементов на странице
          required: false
          schema:
            type: integer
            default: 10
        - name: status
          in: query
          description: Статус карты
          required: false
          schema:
            type: string
            enum: [ ACTIVE, BLOCKED ]
        - name: cardNumber
          in: query
          description: Часть номера карты для поиска
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Список карт с пагинацией
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/CardDto'
                  page:
                    type: integer
                    example: 0
                  size:
                    type: integer
                    example: 10
                  totalElements:
                    type: integer
                    example: 25
                  totalPages:
                    type: integer
                    example: 3
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionBody'
  /api/user/card/{id}:
    get:
      tags:
        - Card
      summary: Получить карту по ID
      operationId: getCardById
      parameters:
        - name: id
          in: path
          required: true
          description: UUID карты
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Карта найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardDto'
        '404':
          description: Карта не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionBody'
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionBody'
  /api/user/card/request_to_block/{id}:
    put:
      tags:
        - Card
      summary: Отправить запрос на блокировку карты по ID
      operationId: requestCardBlockById
      parameters:
        - name: id
          in: path
          required: true
          description: UUID карты, которую нужно заблокировать
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Карта успешно заблокирована
        '404':
          description: Карта не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionBody'
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionBody'
  /api/user/card/balance/{id}:
    get:
      tags:
        - Card
      summary: Получить баланс карты по ID
      operationId: getCardBalance
      parameters:
        - name: id
          in: path
          required: true
          description: UUID карты
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Баланс карты (целое число)
          content:
            text/plain:
              schema:
                type: number
                format: double
                example: 1000.49
        '404':
          description: Карта не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionBody'
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionBody'
  /api/user/card/transfer:
    put:
      tags:
        - Card
      summary: Перевод средств с одной своей карты на другую
      operationId: transferBetweenCards
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fromCardId:
                  type: string
                  format: uuid
                  description: UUID карты-отправителя
                toCardId:
                  type: string
                  format: uuid
                  description: UUID карты-получателя
                amount:
                  type: number
                  format: double
                  description: Сумма перевода
              required:
                - fromCardId
                - toCardId
                - amount
      responses:
        '200':
          description: Перевод успешно выполнен, возвращает новый баланс карты-отправителя
          content:
            text/plain:
              schema:
                type: number
                format: double
                example: 950.50
        '400':
          description: Ошибка перевода (недостаточно средств, неверные карты и т.д.)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionBody'
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionBody'
        '404':
          description: Карта не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionBody'


  /api/public/register:
    post:
      tags:
        - User
      summary: Регистрация нового пользователя
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        '201':
          description: Пользователь успешно зарегистрирован
        '400':
          description: Ошибка валидации (например, логин уже занят)
  /api/public/auth:
    post:
      tags:
        - User
      summary: Аутентификация пользователя и получение токена
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/authDataDto'
      responses:
        '200':
          description: Успешная аутентификация, возвращает JWT токен
          content:
            text/plain:
              schema:
                type: string
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        '401':
          description: Неверный логин или пароль
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionBody'
  /api/admin/user/create:
    post:
      tags:
        - User
      summary: Создать нового пользователя
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        '201':
          description: Пользователь успешно создан
        '400':
          description: Ошибка валидации входных данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionBody'
  /api/admin/user/update/{id}:
    put:
      tags:
        - User
      summary: Обновить данные пользователя по ID
      operationId: updateUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        '200':
          description: Пользователь успешно обновлен
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionBody'
  /api/admin/user/block/{id}:
    put:
      tags:
        - User
      summary: Заблокировать пользователя по ID
      operationId: blockUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Пользователь успешно заблокирован
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionBody'



components:
  schemas:
    CardDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        cardNumber:
          type: string
        ownerName:
          type: string
        expirationDate:
          type: string
          format: date
        status:
          type: string
        balance:
          type: number
          format: double
        createdAt:
          type: string
          format: date-time
      required:
        - cardNumber
        - ownerName
        - expirationDate
        - status
    CardWithUserIdDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        cardNumber:
          type: string
        ownerName:
          type: string
        expirationDate:
          type: string
          format: date
        status:
          type: string
        balance:
          type: number
          format: double
        createdAt:
          type: string
          format: date-time
        userId:
          type: string
          format: uuid
      required:
        - cardNumber
        - ownerName
        - expirationDate
        - status
        - userId
    UserDto:
      type: object
      properties:
        name:
          type: string
        login:
          type: string
        password:
          type: string
      required:
        - login
        - password
    authDataDto:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
      required:
        - login
        - password
    ApiError:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
      required:
        - title
        - description

    ExceptionBody:
      type: object
      properties:
        errors:
          type: array
          description: Errors list
          minItems: 1
          items:
            $ref: '#/components/schemas/ApiError'
      required:
        - errors